### ISSUE TITLE
jenkins user should be added to the 'docker' group in the entrypoint?

### ISSUE THREAD

**Issue by davidcaron** [Ouranosinc/jenkins-ssh-slave#1]
I understand what the entrypoint file is trying to accomplish (add the jenkins user to the docker group) but I'm not sure the result is the one intended... It's like the entrypoint tries to add the user to a new group, with the same id as the docker group outside the image. But to be able to use docker from inside the container, shouldn't the user belong to the docker group inside the container?

The new `docker_from_host` doesn't have any docker permissions, so I don't think it makes sense to add the jenkins user to this group.

https://github.com/Ouranosinc/jenkins-ssh-slave/blob/e931f6c024f18dfd7e7f9d21f2f6858933b998f9/entrypoint_slave#L12

So when I change the entrypoint_slave to this, it works:

``` bash
#!/bin/sh -x 

usermod -G docker -a jenkins

# finally call the same entrypoint as the original base image
/usr/local/bin/setup-sshd "$@"
```

**Comment by tlvu** [comment]
That's odd.

I specifically did this entrypoint because the docker client inside the container was not able to use the docker daemon on the host unless the user inside the container is also member of the docker group on the outside host.

Can you provide output to the following commands:
```
id
getent group | docker
```
both on your host and inside the container.

Edit:
* also output for `docker --version` and `uname -a` both on host and inside container.

**Comment by davidcaron** [comment]
Sorry for the delay:

From the host:
```
ubuntu@daccs-jenkins:~/jenkins-config$ id 
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),109(netdev),110(lxd),999(docker)
ubuntu@daccs-jenkins:~/jenkins-config$ getent group | grep docker 
docker:x:999:ubuntu
ubuntu@daccs-jenkins:~/jenkins-config$ docker --version 
Docker version 19.03.5, build 633a0ea838 
ubuntu@daccs-jenkins:~/jenkins-config$ uname -a 
Linux daccs-jenkins 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

From the container:

```
ubuntu@daccs-jenkins:~/jenkins-config$ ./jenkins-compose.sh exec slave bash 
root@jenkins_slave:/home/jenkins# id 
uid=0(root) gid=0(root) groups=0(root) 
root@jenkins_slave:/home/jenkins# getent group | grep docker 
docker:x:999: 
root@jenkins_slave:/home/jenkins# docker --version 
Docker version 18.09.2, build 6247962 
root@jenkins_slave:/home/jenkins# uname -a 
Linux jenkins_slave 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 GNU/Linux
```

Oh, I see I think I know what is going on...

In the logs of the slave, I get:

```
slave_1   | + addgroup --gid 999 docker_from_host 
slave_1   | addgroup: The GID `999' is already in use.
slave_1   | + usermod -G docker_from_host -a jenkins
slave_1   | usermod: group 'docker_from_host' does not exist
```

So the jenkins user is not added to any groups.

I'll try to submit a PR, I think we should just handle the case where the group ids for docker are the same in the host and in the container.

**Comment by davidcaron** [comment]
@tlvu Somehow I can't add you as a reviewer for this PR ⬆️ I think I don't have the permissions.

**Comment by tlvu** [comment]
Nice diagnostic and you auto-corrected I wanted to `| grep docker` and not just `| docker`.

**Comment by tlvu** [comment]
Close because already fixed by PR https://github.com/Ouranosinc/jenkins-ssh-slave/pull/2
